### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by khannover** [lacymorrow/movie-trailer#3]
Hi,
nice tool. I wonder if there is a way to get trailers only in a specific language, e.g. german.
Even for german movie titles i get trailers with english audio or english subtitles burned in.

Greetz
khannover

**Comment by khannover** [comment]
I just found a workaround for me... just edited lines 31 and 76 of index.js and added the parameter '&language=de_DE' ... maybe you could make this configurable?

**Comment by lacymorrow** [comment]
Thanks for bringing this up! Working to add it soon.
