### ISSUE TITLE
Is there any types for it ?

### ISSUE THREAD

**Issue by moneebalalfi** [lacymorrow/movie-trailer#6]
I'm using typescript with react ..

**Comment by moneebalalfi** [comment]
I just solved typescript issue with **@ts-ignore**
*Like this :*

```
// @ts-ignore
import * as movieTrailer from "movie-trailer";
```
**Thanks! 💻**

**Comment by lacymorrow** [comment]
Thanks for letting us know the solution @moneebalalfi!
