### ISSUE TITLE
Fetching trailer by ID

### ISSUE THREAD

**Issue by Tarek-23** [lacymorrow/movie-trailer#8]
Is there any way to call the second API request directly to fetch the trailer with the TMDB movie id? Do you expect to provide support for this soon?

**Comment by lacymorrow** [comment]
Implemented in the latest version, 2.1.0: https://github.com/lacymorrow/movie-trailer/releases/latest

I've added the `tmdbId` option so you can pass the value yourself, like:
```js
movieTrailer( null, { tmdbId: '161' }
```
